nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    description: 'Authorization: Bearer {jwt}'
                    name: Authorization
                    in: header
        security:
            - Bearer: []
        paths:
            /api/login_check:
                post:
                    tags:
                        - Login
                    summary: Login into the api.
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                                    type: object
                    responses:
                        '200':
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                            refresh_token:
                                                type: string
                        '401':
                            description: Invalid credentials
                        '400':
                            description: Invalid JSON.
                    security: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            -  /register # Accepts routes under /api except /api/doc
